ClientsTable: 
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ClientsTable-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: branchId
        AttributeType: S
      - AttributeName: status
        AttributeType: S
    KeySchema:
      - AttributeName: id
        KeyType: HASH
    GlobalSecondaryIndexes:
      - IndexName: statusAndBranchId
        KeySchema:
          - AttributeName: status
            KeyType: HASH
          - AttributeName: branchId
            KeyType: RANGE
        Projection:
          ProjectionType: ALL